import type { Metadata } from 'next'
import './globals.css'
import { manrope } from './config/font'
import { Provider } from './provider'
import { Sidebar } from './components/sidebar'
import { Header } from './components/header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased ${manrope.variable} font-sans`}>
				<Provider>
					<div className='flex h-screen'>
						<Sidebar />
						<div className='flex grow flex-col'>
							<Header />
							<div className='grow overflow-y-auto px-5 pt-4'>{children}</div>
						</div>
					</div>
				</Provider>
			</body>
		</html>
	)
}
